$(go get github.com/gin-gonic/gin)
$(go get github.com/BurntSushi/toml)
$(go get github.com/go-sql-driver/mysql)
$(export GOPATH=~/.go)
$(export GOROOT=/usr/local/go)
$(export PATH=$GROOT/bin:$PATH)
$(mysql -u root < ./event.sql)
